// Demo data for নাঙ্গলকোট বাজার ব্যবসায়ী সংস্থা.
// NIDs are chosen so their last-6 digits are all distinct (one is 235192 -> /profiles/235192).

export const businessmen = [
  {
    full_name: 'মোহাম্মদ রফিকুল ইসলাম', mobile_number: '01712235192',
    father_name: 'মৃত আব্দুল হাকিম', mother_name: 'রহিমা বেগম', blood_group: 'B+',
    village: 'বক্সগঞ্জ', post_office: 'নাঙ্গলকোট', municipality_or_union: 'নাঙ্গলকোট পৌরসভা',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'রফিক স্টোর, নাঙ্গলকোট বাজার, প্রধান সড়ক',
    business_type: 'মুদি দোকান', trade_license_no: 'TL-NBA-1024', tin_no: '412356789012',
    market_name: 'নাঙ্গলকোট বাজার', owner_name: 'মোহাম্মদ রফিকুল ইসলাম', ward_no: '৩', holding_no: '১১২/ক',
    nid_no: '1990123235192', nominee_name: 'সালমা আক্তার', nominee_relation: 'স্ত্রী', nominee_mobile: '01812235193',
    profile_photo_url: 'https://i.pravatar.cc/400?img=12',
  },
  {
    full_name: 'আব্দুল করিম', mobile_number: '01718784512',
    father_name: 'মৃত নূরুল হক', mother_name: 'জোহরা খাতুন', blood_group: 'O+',
    village: 'ঢালুয়া', post_office: 'ঢালুয়া', municipality_or_union: 'ঢালুয়া ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'করিম বস্ত্রালয়, নতুন বাজার',
    business_type: 'কাপড়ের দোকান', trade_license_no: 'TL-NBA-1088', tin_no: '556677889900',
    market_name: 'নতুন বাজার', owner_name: 'আব্দুল করিম', ward_no: '৫', holding_no: '৪৫',
    nid_no: '1985467784512', nominee_name: 'রাবেয়া বেগম', nominee_relation: 'স্ত্রী', nominee_mobile: '01912784513',
    profile_photo_url: 'https://i.pravatar.cc/400?img=13',
  },
  {
    full_name: 'নূর মোহাম্মদ', mobile_number: '01911301145',
    father_name: 'হাজী ইব্রাহিম', mother_name: 'আমেনা খাতুন', blood_group: 'A+',
    village: 'পেরিয়া', post_office: 'পেরিয়া', municipality_or_union: 'পেরিয়া ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'নূর ফার্মেসী, নাঙ্গলকোট বাজার, হাসপাতাল রোড',
    business_type: 'ফার্মেসী', trade_license_no: 'TL-NBA-1131', tin_no: '223344556677',
    market_name: 'নাঙ্গলকোট বাজার', owner_name: 'নূর মোহাম্মদ', ward_no: '২', holding_no: '৭৮/খ',
    nid_no: '1992881301145', nominee_name: 'ইউসুফ মোহাম্মদ', nominee_relation: 'ছেলে', nominee_mobile: '01711301146',
    profile_photo_url: 'https://i.pravatar.cc/400?img=33',
  },
  {
    full_name: 'শাহ আলম', mobile_number: '01677512067',
    father_name: 'মৃত সোলায়মান মিয়া', mother_name: 'ফিরোজা বেগম', blood_group: 'AB+',
    village: 'হেসাখাল', post_office: 'হেসাখাল', municipality_or_union: 'হেসাখাল ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'আলম ইলেকট্রনিক্স, রেল স্টেশন মার্কেট',
    business_type: 'ইলেকট্রনিক্স', trade_license_no: 'TL-NBA-1177', tin_no: '667788990011',
    market_name: 'রেল স্টেশন মার্কেট', owner_name: 'শাহ আলম', ward_no: '৪', holding_no: '২৩',
    nid_no: '1988334512067', nominee_name: 'নাসরিন আক্তার', nominee_relation: 'স্ত্রী', nominee_mobile: '01977512068',
    profile_photo_url: 'https://i.pravatar.cc/400?img=51',
  },
  {
    full_name: 'জসিম উদ্দিন', mobile_number: '01812223418',
    father_name: 'আব্দুল মালেক', mother_name: 'হালিমা খাতুন', blood_group: 'B-',
    village: 'জোড্ডা', post_office: 'জোড্ডা', municipality_or_union: 'জোড্ডা ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'জসিম জুয়েলার্স, পুরাতন বাজার',
    business_type: 'স্বর্ণকার', trade_license_no: 'TL-NBA-1203', tin_no: '778899001122',
    market_name: 'পুরাতন বাজার', owner_name: 'জসিম উদ্দিন', ward_no: '১', holding_no: '৯',
    nid_no: '1979556223418', nominee_name: 'মোরশেদা বেগম', nominee_relation: 'স্ত্রী', nominee_mobile: '01712223419',
    profile_photo_url: 'https://i.pravatar.cc/400?img=52',
  },
  {
    full_name: 'হারুন অর রশিদ', mobile_number: '01715908734',
    father_name: 'মৃত আবুল হাশেম', mother_name: 'সুফিয়া খাতুন', blood_group: 'O-',
    village: 'রায়কোট', post_office: 'রায়কোট', municipality_or_union: 'রায়কোট (উত্তর) ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'রশিদ হার্ডওয়্যার, নাঙ্গলকোট বাজার',
    business_type: 'হার্ডওয়্যার', trade_license_no: 'TL-NBA-1250', tin_no: '889900112233',
    market_name: 'নাঙ্গলকোট বাজার', owner_name: 'হারুন অর রশিদ', ward_no: '৬', holding_no: '১৫৪',
    nid_no: '1983019445690', nominee_name: 'রফিক আহমেদ', nominee_relation: 'ছেলে', nominee_mobile: '01815908735',
    profile_photo_url: 'https://i.pravatar.cc/400?img=53',
  },
  {
    full_name: 'আবুল কালাম আজাদ', mobile_number: '01919137852',
    father_name: 'মৃত মোবারক আলী', mother_name: 'রোকেয়া বেগম', blood_group: 'A-',
    village: 'মৌকরা', post_office: 'মৌকরা', municipality_or_union: 'মৌকরা ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'আজাদ হোটেল ও রেস্টুরেন্ট, নতুন বাজার',
    business_type: 'রেস্টুরেন্ট', trade_license_no: 'TL-NBA-1299', tin_no: '990011223344',
    market_name: 'নতুন বাজার', owner_name: 'আবুল কালাম আজাদ', ward_no: '৩', holding_no: '৬৭/গ',
    nid_no: '1991660137852', nominee_name: 'শাহনাজ পারভীন', nominee_relation: 'স্ত্রী', nominee_mobile: '01719137853',
    profile_photo_url: 'https://i.pravatar.cc/400?img=14',
  },
  {
    full_name: 'মিজানুর রহমান', mobile_number: '01611619073',
    father_name: 'আব্দুস সাত্তার', mother_name: 'মনোয়ারা বেগম', blood_group: 'B+',
    village: 'বটতলী', post_office: 'নাঙ্গলকোট', municipality_or_union: 'নাঙ্গলকোট পৌরসভা',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'মিজান টেলিকম, নাঙ্গলকোট বাজার',
    business_type: 'মোবাইল সার্ভিসিং', trade_license_no: 'TL-NBA-1322', tin_no: '101112131415',
    market_name: 'নাঙ্গলকোট বাজার', owner_name: 'মিজানুর রহমান', ward_no: '৭', holding_no: '৮৮',
    nid_no: '1987245619073', nominee_name: 'তানিয়া আক্তার', nominee_relation: 'স্ত্রী', nominee_mobile: '01611619074',
    profile_photo_url: 'https://i.pravatar.cc/400?img=15',
  },
  {
    full_name: 'সিরাজুল ইসলাম', mobile_number: '01717480561',
    father_name: 'মৃত আব্দুল বারী', mother_name: 'ছালেহা খাতুন', blood_group: 'O+',
    village: 'ধাতিসর', post_office: 'নাঙ্গলকোট', municipality_or_union: 'নাঙ্গলকোট পৌরসভা',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'ইসলামিয়া লাইব্রেরী, নাঙ্গলকোট বাজার',
    business_type: 'বইয়ের দোকান', trade_license_no: 'TL-NBA-1355', tin_no: '121314151617',
    market_name: 'নাঙ্গলকোট বাজার', owner_name: 'সিরাজুল ইসলাম', ward_no: '২', holding_no: '৩৪',
    nid_no: '1994103480561', nominee_name: 'আব্দুল্লাহ আল মামুন', nominee_relation: 'ছেলে', nominee_mobile: '01817480562',
    profile_photo_url: 'https://i.pravatar.cc/400?img=60',
  },
  {
    full_name: 'দেলোয়ার হোসেন', mobile_number: '01811726304',
    father_name: 'মৃত হাবিবুর রহমান', mother_name: 'আয়েশা বেগম', blood_group: 'AB-',
    village: 'ঢালুয়া', post_office: 'ঢালুয়া', municipality_or_union: 'ঢালুয়া ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'দেলোয়ার সুজ, পুরাতন বাজার',
    business_type: 'জুতার দোকান', trade_license_no: 'TL-NBA-1390', tin_no: '131415161718',
    market_name: 'পুরাতন বাজার', owner_name: 'দেলোয়ার হোসেন', ward_no: '৫', holding_no: '১০১',
    nid_no: '1982559726304', nominee_name: 'নার্গিস আক্তার', nominee_relation: 'স্ত্রী', nominee_mobile: '01911726305',
    profile_photo_url: 'https://i.pravatar.cc/400?img=61',
  },
  {
    full_name: 'কামাল উদ্দিন', mobile_number: '01715053219',
    father_name: 'মৃত আবুল বাশার', mother_name: 'ফাতেমা বেগম', blood_group: 'A+',
    village: 'হেসাখাল', post_office: 'হেসাখাল', municipality_or_union: 'হেসাখাল ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'কামাল ট্রেডার্স (সার-বীজ), রেল স্টেশন মার্কেট',
    business_type: 'সার-বীজ ও কীটনাশক', trade_license_no: 'TL-NBA-1412', tin_no: '141516171819',
    market_name: 'রেল স্টেশন মার্কেট', owner_name: 'কামাল উদ্দিন', ward_no: '৮', holding_no: '১৯',
    nid_no: '1996887053219', nominee_name: 'হাসান মাহমুদ', nominee_relation: 'ছেলে', nominee_mobile: '01815053220',
    profile_photo_url: 'https://i.pravatar.cc/400?img=54',
  },
  {
    full_name: 'ফরিদ আহমেদ', mobile_number: '01917619073',
    father_name: 'মৃত আব্দুল জলিল', mother_name: 'শামসুন্নাহার', blood_group: 'B+',
    village: 'পেরিয়া', post_office: 'পেরিয়া', municipality_or_union: 'পেরিয়া ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'ফরিদ কসমেটিক্স, নতুন বাজার',
    business_type: 'কসমেটিক্স', trade_license_no: 'TL-NBA-1455', tin_no: '151617181920',
    market_name: 'নতুন বাজার', owner_name: 'ফরিদ আহমেদ', ward_no: '৪', holding_no: '৫৬',
    nid_no: '1990774628190', nominee_name: 'রুবিনা আক্তার', nominee_relation: 'স্ত্রী', nominee_mobile: '01717628191',
    profile_photo_url: 'https://i.pravatar.cc/400?img=16',
  },
];

export const registrationRequests = [
  {
    full_name: 'আনোয়ার হোসেন', mobile_number: '01712667788',
    father_name: 'মৃত ছিদ্দিক মিয়া', mother_name: 'রেহানা বেগম', blood_group: 'O+',
    village: 'বটতলী', post_office: 'নাঙ্গলকোট', municipality_or_union: 'নাঙ্গলকোট পৌরসভা',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'আনোয়ার টি স্টল, নাঙ্গলকোট বাজার',
    business_type: 'চায়ের দোকান', trade_license_no: '', tin_no: '',
    market_name: 'নাঙ্গলকোট বাজার', owner_name: 'আনোয়ার হোসেন', ward_no: '৩', holding_no: '২০১',
    nid_no: '1993445667788', nominee_name: 'রহিমা বেগম', nominee_relation: 'মাতা', nominee_mobile: '01812667789',
    profile_photo_url: 'https://i.pravatar.cc/400?img=17',
    transaction_id: 'TXN8F2K9L4TQ7', status: 'pending',
  },
  {
    full_name: 'বেলাল হোসেন', mobile_number: '01911455990',
    father_name: 'আব্দুল মান্নান', mother_name: 'নূরজাহান বেগম', blood_group: 'A+',
    village: 'ঢালুয়া', post_office: 'ঢালুয়া', municipality_or_union: 'ঢালুয়া ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'বেলাল ফল ভান্ডার, নতুন বাজার',
    business_type: 'ফলের দোকান', trade_license_no: '', tin_no: '',
    market_name: 'নতুন বাজার', owner_name: 'বেলাল হোসেন', ward_no: '৫', holding_no: '৭৭',
    nid_no: '1990334455990', nominee_name: 'শিরিন আক্তার', nominee_relation: 'স্ত্রী', nominee_mobile: '01711455991',
    profile_photo_url: 'https://i.pravatar.cc/400?img=18',
    transaction_id: 'TXN7Q4TZ2WX9', status: 'pending',
  },
  {
    full_name: 'রাসেল মিয়া', mobile_number: '01812233445',
    father_name: 'কবির মিয়া', mother_name: 'রীনা বেগম', blood_group: 'B+',
    village: 'পেরিয়া', post_office: 'পেরিয়া', municipality_or_union: 'পেরিয়া ইউনিয়ন',
    upazila: 'নাঙ্গলকোট', district: 'কুমিল্লা',
    current_business_name_address: 'রাসেল ভ্যারাইটিজ, নাঙ্গলকোট বাজার',
    business_type: 'ভ্যারাইটি স্টোর', trade_license_no: '', tin_no: '',
    market_name: 'নাঙ্গলকোট বাজার', owner_name: 'রাসেল মিয়া', ward_no: '২', holding_no: '৪১',
    nid_no: '1988112233445', nominee_name: 'কবির মিয়া', nominee_relation: 'পিতা', nominee_mobile: '01912233446',
    profile_photo_url: 'https://i.pravatar.cc/400?img=19',
    transaction_id: 'TXN0000INVALID', status: 'rejected', reject_reason: 'ট্রানজেকশন আইডি যাচাই করা যায়নি। সঠিক তথ্য দিয়ে পুনরায় আবেদন করুন।',
  },
];

export const galleryImages = [
  { image_url: 'https://picsum.photos/seed/nba-market1/1000/700', caption_bn: 'নাঙ্গলকোট বাজারের প্রধান সড়ক', caption_en: 'Main road of Nangalkot Bazar', sort_order: 1 },
  { image_url: 'https://picsum.photos/seed/nba-meeting/1000/700', caption_bn: 'সংস্থার বার্ষিক সাধারণ সভা', caption_en: 'Annual general meeting of the association', sort_order: 2 },
  { image_url: 'https://picsum.photos/seed/nba-shop/1000/700', caption_bn: 'সদস্যদের দোকানপাট', caption_en: 'Member shops in the market', sort_order: 3 },
  { image_url: 'https://picsum.photos/seed/nba-eid/1000/700', caption_bn: 'ঈদ পুনর্মিলনী অনুষ্ঠান', caption_en: 'Eid reunion event', sort_order: 4 },
  { image_url: 'https://picsum.photos/seed/nba-relief/1000/700', caption_bn: 'শীতবস্ত্র বিতরণ কর্মসূচি', caption_en: 'Winter clothing distribution programme', sort_order: 5 },
  { image_url: 'https://picsum.photos/seed/nba-committee/1000/700', caption_bn: 'কার্যনির্বাহী কমিটির সদস্যবৃন্দ', caption_en: 'Executive committee members', sort_order: 6 },
  { image_url: 'https://picsum.photos/seed/nba-night/1000/700', caption_bn: 'সন্ধ্যায় বাজারের দৃশ্য', caption_en: 'The market in the evening', sort_order: 7 },
];

export const pageContent = [
  {
    page_key: 'home',
    title_bn: 'নাঙ্গলকোট বাজার ব্যবসায়ী সংস্থা',
    title_en: 'Nangalkot Bazar Business Association',
    subtitle_bn: 'স্থানীয় ব্যবসায়ীদের একটি নিবন্ধিত সংগঠন — সকল সদস্যের তথ্য এক জায়গায়।',
    subtitle_en: 'A registered organization of local businessmen — every member’s information in one place.',
    body_bn: 'আমাদের সংস্থা নাঙ্গলকোট বাজারের ব্যবসায়ীদের ঐক্য, কল্যাণ ও পারস্পরিক সহযোগিতার লক্ষ্যে প্রতিষ্ঠিত। এই প্ল্যাটফর্মে সকল নিবন্ধিত সদস্যের তথ্য সহজে খুঁজে পাওয়া যায়।',
    body_en: 'Our association was formed to promote the unity, welfare and mutual cooperation of the businessmen of Nangalkot Bazar. This platform lets anyone easily find the information of every registered member.',
    extra: { cta_bn: 'সদস্য হিসেবে আবেদন করুন', cta_en: 'Apply for membership' },
  },
  {
    page_key: 'about',
    title_bn: 'আমাদের সম্পর্কে',
    title_en: 'About Us',
    subtitle_bn: 'ব্যবসায়ীদের কল্যাণে নিবেদিত একটি সংগঠন',
    subtitle_en: 'An organization dedicated to the welfare of businessmen',
    body_bn: '## আমাদের পরিচিতি\n\nনাঙ্গলকোট বাজার ব্যবসায়ী সংস্থা কুমিল্লা জেলার নাঙ্গলকোট উপজেলার ব্যবসায়ীদের একটি নিবন্ধিত সংগঠন। ২০১০ সাল থেকে আমরা স্থানীয় ব্যবসায়ীদের অধিকার রক্ষা, ব্যবসায়িক পরিবেশ উন্নয়ন এবং সামাজিক কল্যাণমূলক কাজে নিয়োজিত।\n\n## আমাদের লক্ষ্য\n\n- সকল ব্যবসায়ীর ঐক্য ও সংহতি বৃদ্ধি\n- ব্যবসায়িক সমস্যা সমাধানে সহযোগিতা\n- সদস্যদের কল্যাণে বিভিন্ন কর্মসূচি বাস্তবায়ন\n- বাজারের শৃঙ্খলা ও নিরাপত্তা নিশ্চিতকরণ\n\n## আমাদের অর্জন\n\nবর্তমানে সংস্থার শতাধিক নিবন্ধিত সদস্য রয়েছে। প্রতি বছর আমরা ঈদ পুনর্মিলনী, শীতবস্ত্র বিতরণ ও বিভিন্ন সামাজিক কর্মসূচি আয়োজন করে থাকি।',
    body_en: '## Who we are\n\nThe Nangalkot Bazar Business Association is a registered organization of the businessmen of Nangalkot Upazila, Cumilla. Since 2010 we have worked to protect the rights of local traders, improve the business environment, and carry out social welfare activities.\n\n## Our goals\n\n- Strengthen the unity and solidarity of all businessmen\n- Cooperate in resolving business problems\n- Run welfare programmes for members\n- Ensure order and security in the market\n\n## Our achievements\n\nThe association currently has over a hundred registered members. Every year we organize Eid reunions, winter clothing distribution and various social programmes.',
    extra: {},
  },
  {
    page_key: 'contact',
    title_bn: 'যোগাযোগ',
    title_en: 'Contact Us',
    subtitle_bn: 'আমাদের সাথে যোগাযোগ করুন',
    subtitle_en: 'Get in touch with us',
    body_bn: 'যেকোনো প্রয়োজনে আমাদের অফিসে যোগাযোগ করুন অথবা নিচের ফর্মটি পূরণ করে বার্তা পাঠান। আমরা দ্রুততম সময়ে উত্তর দেওয়ার চেষ্টা করব।',
    body_en: 'For any need, please contact our office or send us a message using the form below. We will try to respond as quickly as possible.',
    extra: {
      phone: '01812345678',
      email: 'info@nangalkotbazar.org',
      address_bn: 'সংস্থা কার্যালয়, নাঙ্গলকোট বাজার, নাঙ্গলকোট, কুমিল্লা',
      address_en: 'Association Office, Nangalkot Bazar, Nangalkot, Cumilla',
      facebook: 'https://facebook.com/nangalkotbazar',
    },
  },
  {
    page_key: 'rules',
    title_bn: 'সংস্থার নিয়মকানুন',
    title_en: 'Association Rules',
    subtitle_bn: 'সদস্যদের জন্য প্রযোজ্য নিয়মাবলী',
    subtitle_en: 'Rules applicable to all members',
    body_bn: '## সদস্যপদ ও নিয়মাবলী\n\n১. প্রত্যেক সদস্যকে অবশ্যই নাঙ্গলকোট বাজারের একজন বৈধ ব্যবসায়ী হতে হবে।\n\n২. সদস্য হতে হলে নির্ধারিত রেজিষ্ট্রেশন ফি ৫০০ (পাঁচশত) টাকা পরিশোধ করতে হবে।\n\n৩. রেজিষ্ট্রেশনের সময় সঠিক ও সত্য তথ্য প্রদান করতে হবে; ভুল তথ্য প্রদান করলে সদস্যপদ বাতিল হবে।\n\n৪. প্রত্যেক সদস্যকে জাতীয় পরিচয়পত্র ও ট্রেড লাইসেন্সের তথ্য প্রদান করতে হবে।\n\n৫. সংস্থার সকল সভায় সদস্যদের উপস্থিত থাকা বাঞ্ছনীয়।\n\n৬. বাজারের শৃঙ্খলা ও পরিচ্ছন্নতা বজায় রাখা প্রত্যেক সদস্যের দায়িত্ব।\n\n৭. কোনো সদস্য অসদাচরণ বা সংস্থার ভাবমূর্তি ক্ষুণ্ন করলে কার্যনির্বাহী কমিটি ব্যবস্থা গ্রহণ করবে।\n\n৮. বার্ষিক চাঁদা যথাসময়ে পরিশোধ করতে হবে।',
    body_en: '## Membership and rules\n\n1. Every member must be a legitimate businessman of Nangalkot Bazar.\n\n2. To become a member, the fixed registration fee of 500 (five hundred) Taka must be paid.\n\n3. Accurate and truthful information must be provided during registration; membership will be cancelled for false information.\n\n4. Every member must provide their National ID and trade licence details.\n\n5. Members are expected to attend all meetings of the association.\n\n6. Maintaining order and cleanliness of the market is the responsibility of every member.\n\n7. If any member misbehaves or damages the reputation of the association, the executive committee will take action.\n\n8. The annual subscription must be paid on time.',
    extra: {},
  },
];

export const siteSettings = {
  org_name_bn: 'নাঙ্গলকোট বাজার ব্যবসায়ী সংস্থা',
  org_name_en: 'Nangalkot Bazar Business Association',
  bkash_number: '01812345678',
  registration_fee: 500,
  active_theme: 'emerald',
  logo_url: null,
  hero_images: [
    // The association's own photo (uploaded to Cloudinary).
    { url: 'https://res.cloudinary.com/ldbnzjyk/image/upload/v1783423773/nangalkot-bazar/misc/pfaeb76vh65v5nph3xzj.jpg', public_id: 'nangalkot-bazar/misc/pfaeb76vh65v5nph3xzj' },
    // Placeholder market photos — the admin can remove/replace these to build the carousel.
    { url: 'https://picsum.photos/seed/nba-bazar-street/1600/720', public_id: null },
    { url: 'https://picsum.photos/seed/nba-bazar-shops/1600/720', public_id: null },
  ],
  contact_email: 'info@nangalkotbazar.org',
  contact_phone: '01812345678',
  contact_address_bn: 'সংস্থা কার্যালয়, নাঙ্গলকোট বাজার, নাঙ্গলকোট, কুমিল্লা',
  contact_address_en: 'Association Office, Nangalkot Bazar, Nangalkot, Cumilla',
  facebook_url: 'https://facebook.com/nangalkotbazar',
};

export const contactMessages = [
  {
    name: 'সাইফুল ইসলাম', email: 'saiful@example.com', phone: '01700000001',
    subject: 'সদস্য হতে চাই', message: 'আমি নাঙ্গলকোট বাজারে একটি নতুন দোকান দিয়েছি। সদস্য হওয়ার নিয়ম জানতে চাই।', is_read: false,
  },
  {
    name: 'জাহিদ হাসান', email: '', phone: '01700000002',
    subject: 'সভার সময়সূচি', message: 'আগামী মাসের সাধারণ সভা কবে হবে জানালে উপকৃত হব।', is_read: true,
  },
];
